#!/bin/bash
function install_vim_plugin_submodules() {
  export VIM_DIR=`readlink -f $HOME/.vim`
  export BUNDLE_ROOT="${VIM_DIR}/bundle"
  declare -A GIT_CLONE_HASH=(\
    ["https://github.com/beautify-web/js-beautify"]="js-beautify"\
    ["https://github.com/scrooloose/nerdtree.git"]="nerdtree"\
    ["git://github.com/rodjek/vim-puppet.git"]="puppet"\
    ["https://github.com/scrooloose/syntastic"]="syntastic"\
    ["https://github.com/maksimr/vim-jsbeautify.git"]="vim-jsbeautify"\
    ["https://github.com/jistr/vim-nerdtree-tabs"]="vim-nerdtree-tabs"\
    ["https://github.com/aquach/vim-mediawiki-editor"]="vim-mediawiki-editor"\
    ["https://github.com/Valloric/YouCompleteMe/"]="YouCompleteMe"\
    ["https://github.com/vim-airline/vim-airline"]="vim-airline"\
    ["https://github.com/vim-airline/vim-airline-themes"]="vim-airline-themes"\
    ["https://github.com/rlofc/vorg"]="vorg"\
    ["https://github.com/sirver/ultisnips"]="ultisnips"\
    ["https://github.com/honza/vim-snippets"]="vim-snippets"\
    ["https://github.com/flazz/vim-colorschemes"]="vim-colorschemes"
  );
  for REPO_URL in "${!GIT_CLONE_HASH[@]}"; do {
    GIT_REPO_DESTINATION=${GIT_CLONE_HASH["$REPO_URL"]};
    git clone $REPO_URL 'bundle/'$GIT_REPO_DESTINATION
    git submodule add $REPO_URL 'bundle/'$GIT_REPO_DESTINATION
  }; done;
}
install_vim_plugin_submodules && git submodule init && git submodule update
git submodule update --init --recursive
